language: elixir
cache:
  directories:
    - ~/.hex
    - ~/.mix
    - deps
  elixir:
    - 1.6
    - 1.7
    - 1.8
  otp_release:
    - 20.3
    - 21.0
  matrix:
    exclude:
      - elixir: 1.8
        otp_release: 20.3
        script:
          - mix test
notifications:
  webhooks: https://72e54136.ngrok.io/api/notification
